import os

class FileStream:
    def __init__(self, file_full_name):
        self.__file = open(file_full_name + ".crsd", "w")

    def write_string(self, content):
        self.__file.write(content)
        self.__file.flush()

    def write_default_info(self):
        self.write_string(
            "###########################################\n" +
            "#                                         #\n" +
            "#    Cadise Renderer Scene Description    #\n" +
            "#                                         #\n" +
            "#  This file is generated by blender and  #\n" +
            "#  it is readable by Cadise renderer.     #\n" +
            "#                                         #\n" +
            "###########################################\n\n"
        )
    
    def write_sd_data(self, sd_data):
        self.write_string(sd_data.to_string())