import os

class FileStream:
    def __init__(self, file_full_name):
        self.__file = open(file_full_name + ".crsd", "w")

    def write_default_info(self):
        self.__file.write(
            "###########################################\n" +
            "#                                         #\n" +
            "#    Cadise Renderer Scene Description    #\n" +
            "#                                         #\n" +
            "#  This file is generated by blender and  #\n" +
            "#  it is readable by Cadise renderer.     #\n" +
            "#                                         #\n" +
            "###########################################\n\n"
        )